INSERT INTO Breed (SELECT * FROM L305_karen.BREED)
go
INSERT INTO Owner (SELECT * FROM L305_karen.OWNER)
go
INSERT INTO Kennel (SELECT * FROM L305_karen.KENNEL)
go
INSERT INTO Show (SELECT * FROM L305_karen.SHOW)
go
INSERT INTO Dog (SELECT * FROM L305_karen.DOG)
go
INSERT INTO Attendance (SELECT * FROM L305_karen.ATTENDANCE)
